apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: networks.samplecrd.x-k8s.io
spec:
  group: samplecrd.x-k8s.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                cidr:
                  type: string
                gateway:
                  type: string
  names:
    kind: Network
    singular: network
    plural: networks
    shortNames:
      - nw
  scope: Namespaced